package CenterModule;

/**
* CenterModule/CenterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Center.idl
* Friday, June 8, 2018 5:26:10 PM EDT
*/

public final class CenterHolder implements org.omg.CORBA.portable.Streamable
{
  public CenterModule.Center value = null;

  public CenterHolder ()
  {
  }

  public CenterHolder (CenterModule.Center initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CenterModule.CenterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CenterModule.CenterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CenterModule.CenterHelper.type ();
  }

}
