package CenterModule;


/**
* CenterModule/CenterPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Center.idl
* Friday, June 8, 2018 5:26:10 PM EDT
*/

public abstract class CenterPOA extends org.omg.PortableServer.Servant
 implements CenterModule.CenterOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createTRecord", new java.lang.Integer (0));
    _methods.put ("createSRecord", new java.lang.Integer (1));
    _methods.put ("getRecordCounts", new java.lang.Integer (2));
    _methods.put ("editRecord", new java.lang.Integer (3));
    _methods.put ("transferRecord", new java.lang.Integer (4));
    _methods.put ("login", new java.lang.Integer (5));
    _methods.put ("logout", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CenterModule/Center/createTRecord
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String specialization = in.read_string ();
         String location = in.read_string ();
         String ManagerID = in.read_string ();
         int mode = in.read_long ();
         String recordID = in.read_string ();
         String $result = null;
         $result = this.createTRecord (firstName, lastName, address, phone, specialization, location, ManagerID, mode, recordID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CenterModule/Center/createSRecord
       {
         String firstName = in.read_string ();
         String lasName = in.read_string ();
         String coursesRegistered = in.read_string ();
         String status = in.read_string ();
         String statusDate = in.read_string ();
         String ManagerID = in.read_string ();
         int mode = in.read_long ();
         String recordID = in.read_string ();
         String $result = null;
         $result = this.createSRecord (firstName, lasName, coursesRegistered, status, statusDate, ManagerID, mode, recordID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // CenterModule/Center/getRecordCounts
       {
         String recordType = in.read_string ();
         String ManagerID = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (recordType, ManagerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // CenterModule/Center/editRecord
       {
         String recordID = in.read_string ();
         String filedName = in.read_string ();
         String newValue = in.read_string ();
         String ManagerID = in.read_string ();
         String $result = null;
         $result = this.editRecord (recordID, filedName, newValue, ManagerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // CenterModule/Center/transferRecord
       {
         String recordID = in.read_string ();
         String remoteCenterServer = in.read_string ();
         String ManagerID = in.read_string ();
         String $result = null;
         $result = this.transferRecord (recordID, remoteCenterServer, ManagerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // CenterModule/Center/login
       {
         String ManagerID = in.read_string ();
         int $result = (int)0;
         $result = this.login (ManagerID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 6:  // CenterModule/Center/logout
       {
         String ManagerID = in.read_string ();
         int $result = (int)0;
         $result = this.logout (ManagerID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CenterModule/Center:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Center _this() 
  {
    return CenterHelper.narrow(
    super._this_object());
  }

  public Center _this(org.omg.CORBA.ORB orb) 
  {
    return CenterHelper.narrow(
    super._this_object(orb));
  }


} // class CenterPOA
