module CenterModule{
    interface Center{
        string createTRecord(in string firstName,in string lastName,in string address,in string phone,in string specialization,in string location,in string ManagerID,in long mode,in string recordID);
        string createSRecord(in string firstName, in string lasName, in string coursesRegistered, in string status, in string statusDate, in string ManagerID, in long mode, in string recordID);
        string getRecordCounts(in string recordType, in string ManagerID);
        string editRecord(in string recordID, in string filedName, in string newValue, in string ManagerID);
        string transferRecord(in string recordID, in string remoteCenterServer, in string ManagerID);
        long login(in string ManagerID);
        long logout(in string ManagerID);
    };
};